/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-01 at 15:33:47 UTC 
 * Modify at your own risk.
 */

package com.travellog.entryendpoint.model;

/**
 * Model definition for EntryendpointEntry.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the entryendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EntryendpointEntry extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> blobkeys;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateCreated;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> hashtags;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String poster;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tripPoster;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getBlobkeys() {
    return blobkeys;
  }

  /**
   * @param blobkeys blobkeys or {@code null} for none
   */
  public EntryendpointEntry setBlobkeys(java.util.List<java.lang.String> blobkeys) {
    this.blobkeys = blobkeys;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateCreated() {
    return dateCreated;
  }

  /**
   * @param dateCreated dateCreated or {@code null} for none
   */
  public EntryendpointEntry setDateCreated(com.google.api.client.util.DateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public EntryendpointEntry setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getHashtags() {
    return hashtags;
  }

  /**
   * @param hashtags hashtags or {@code null} for none
   */
  public EntryendpointEntry setHashtags(java.util.List<java.lang.String> hashtags) {
    this.hashtags = hashtags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public EntryendpointEntry setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public EntryendpointEntry setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPoster() {
    return poster;
  }

  /**
   * @param poster poster or {@code null} for none
   */
  public EntryendpointEntry setPoster(java.lang.String poster) {
    this.poster = poster;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public EntryendpointEntry setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTripPoster() {
    return tripPoster;
  }

  /**
   * @param tripPoster tripPoster or {@code null} for none
   */
  public EntryendpointEntry setTripPoster(java.lang.String tripPoster) {
    this.tripPoster = tripPoster;
    return this;
  }

  @Override
  public EntryendpointEntry set(String fieldName, Object value) {
    return (EntryendpointEntry) super.set(fieldName, value);
  }

  @Override
  public EntryendpointEntry clone() {
    return (EntryendpointEntry) super.clone();
  }

}
